const CATALOG_DATA = {
  tofu: {
    name: "TOFU",
    tagline: "Thailand Skincare & Beauty",
    accent: "#0EA5A5",
    accent2: "#EC4899",
    products: [
      { id:"tofu_01", name:"Tofu Precious Moisturizing", desc:"Body lotion dengan kandungan niacinamide.", price:"Rp 155.000" },
      { id:"tofu_02", name:"Tofu Milk Plus Biru", desc:"Brightening body lotion, 400gr.", price:"Rp 175.000" },
      { id:"tofu_03", name:"Tofu MP Peach", desc:"Lotion melembapkan dengan SPF, melindungi dari sinar UV.", price:"Rp 190.000" },
      { id:"tofu_04", name:"Tofu Body Lotion", desc:"Triple pelembap, bagus untuk kulit kering.", price:"Rp 245.000" },
      { id:"tofu_05", name:"Tofu Facial Wash MP (Putih)", desc:"Membersihkan wajah tanpa bikin kering atau ketarik.", price:"Rp 175.000 (100ml)" },
      { id:"tofu_06", name:"Tofu Facial Wash MP (Hijau)", desc:"Facial wash untuk wajah berjerawat, review bagus.", price:"Rp 180.000" },
      { id:"tofu_07", name:"Tofu Walnut's CC", desc:"Handbody dengan SPF untuk melindungi dari sinar UV.", price:"Rp 185.000 (200ml)" },
      { id:"tofu_08", name:"Tofu Nano White Dose", desc:"Serum 50x whitening, mencerahkan & meratakan warna kulit.", price:"Rp 195.000 (60ml)" },
      { id:"tofu_09", name:"Chupa Chups Soap", desc:"Sabun aroma permen Chupa Chups.", price:"Rp 55.000" },
      { id:"tofu_10", name:"Vaseline Handcream", desc:"Bikin tangan halus & lembut.", price:"Rp 75.000" },
      { id:"tofu_11", name:"Joji Urea Cream", desc:"Melembapkan & menghaluskan kulit kaki kering pecah-pecah.", price:"Rp 100.000 (50gr)" },
      { id:"tofu_12", name:"Serum Vit E Baby Face", desc:"Mengurangi kerutan, kemerahan & bintik hitam.", price:"Rp 115.000 (30ml)" },
      { id:"tofu_13", name:"Precious Skin Thailand Vit C Lemon", desc:"Serum wajah dengan ekstrak lemon, mengembalikan kelembapan.", price:"Rp 110.000 (50ml)" },
      { id:"tofu_14", name:"Tofu Kplus Serum", desc:"Hyaluronic acid, melembapkan & mencerahkan kulit.", price:"Rp 150.000 (20ml)" },
      { id:"tofu_15", name:"Tofu Day Cream Kplus", desc:"Hyaluronic acid, melembapkan & mencerahkan kulit.", price:"Rp 150.000" },
      { id:"tofu_16", name:"Tofu Night Cream Kplus", desc:"Hyaluronic acid, melembapkan & mencerahkan kulit.", price:"Rp 160.000" },
      { id:"tofu_17", name:"Poy Sian Roll On", desc:"Minyak angin roll on khas Thailand.", price:"Rp 50.000 (1pcs) / Rp 135.000 (3pcs)" },
      { id:"tofu_18", name:"Vapex Black Inhaler", desc:"Inhaler angin khas Thailand.", price:"Rp 125.000 (6pcs)" },
      { id:"tofu_19", name:"Tiger Poy Sian Peppermint Inhaler", desc:"Inhaler peppermint, isi 6pcs.", price:"Rp 110.000 (6pcs)" },
      { id:"tofu_20", name:"Golden Cup Inhaler", desc:"Inhaler khas Thailand, isi 6pcs.", price:"Rp 110.000 (6pcs)" },
      { id:"tofu_21", name:"YokoYoko", desc:"Meredakan pegal, linu & nyeri otot leher, bahu, punggung.", price:"Rp 165.000" },
      { id:"tofu_22", name:"Hair Tonik Genive", desc:"Mengurangi kerontokan & menjaga akar rambut sehat.", price:"Rp 95.000 (120ml)" },
      { id:"tofu_23", name:"In2it Primer Glow", desc:"Base makeup, tidak mudah luntur, SPF 25 PA++++.", price:"Rp 185.000" },
      { id:"tofu_24", name:"In2it Primer", desc:"Cocok untuk kulit berminyak (matte) atau kering (glow).", price:"Rp 180.000" },
      { id:"tofu_25", name:"Taoyeablok", desc:"Deodorant powder kaki, menghilangkan bau, 2 varian.", price:"Rp 50.000 (30gr)" },
      { id:"tofu_26", name:"Roll On Vitamin E", desc:"Roll on dengan kandungan vitamin E.", price:"Rp 50.000" },
      { id:"tofu_27", name:"Top Country Deodorant for Man", desc:"Wangi maskulin, menahan keringat berlebih.", price:"Rp 60.000–100.000" },
      { id:"tofu_28", name:"Chupa Chups Toothpaste", desc:"Odol 1500ppm fluoride, cegah kerusakan gigi.", price:"Rp 80.000" },
      { id:"tofu_29", name:"Kodomo Toothpaste", desc:"Odol anak 1000ppm fluoride.", price:"Rp 65.000" },
      { id:"tofu_30", name:"Rasyan Herbal Clove Toothpaste", desc:"Odol herbal cengkeh, bikin napas segar.", price:"Rp 45.000–75.000" },
      { id:"tofu_31", name:"BRW Eyes Brow Shadow", desc:"Banyak dipakai MUA, 3 varian warna.", price:"Rp 120.000" },
      { id:"tofu_32", name:"Gold Princess Food Patch", desc:"Patch koyo herbal Thailand.", price:"Rp 80.000" },
      { id:"tofu_33", name:"TOFU (Joji EDP 45ml)", desc:"Eau de parfum 45ml.", price:"Rp 265.000" },
      { id:"tofu_34", name:"Cathy Doll Cleansing Gel", desc:"Orange: cerah & glowing. Hijau: adem & gentle.", price:"Rp 110.000–125.000" },
      { id:"tofu_35", name:"TOFU 03", desc:"Best seller, bikin wajah cerah.", price:"Rp 150.000" },
      { id:"tofu_36", name:"Tofu Body Lotion 40x", desc:"Cepat habis, cocok untuk kulit kering.", price:"Rp 250.000 (250gr)" }
    ]
  },
  butterfly: {
    name: "BUTTERFLY",
    tagline: "Thai Perfume Original",
    accent: "#8B2F8E",
    accent2: "#D4AF37",
    products: [
      { id:"butterfly_01", name:"Butterfly Parfum Original (Cherry & Saffron)", desc:"Aroma manis memikat, dipadu almond, cengkeh & melati.", price:"Rp 295.000 (10ml) / Rp 895.000 (60ml)" },
      { id:"butterfly_02", name:"Butterfly Crystal Deodorant", desc:"Aroma vanilla old money, manis dan hangat.", price:"Rp 295.000 (10ml) / Rp 900.000 (60ml)" },
      { id:"butterfly_03", name:"Butterfly Parfum Original (Mawar)", desc:"Aroma mawar manis segar, cocok suasana romantis.", price:"Rp 295.000 (10ml) / Rp 900.000 (60ml)" },
      { id:"butterfly_04", name:"Butterfly Parfum Original (Unisex)", desc:"Bisa dipakai cewek & cowok, aroma hangat memikat.", price:"Rp 295.000 (10ml) / Rp 900.000 (60ml)" },
      { id:"butterfly_05", name:"Butterfly Parfum Original (Agarwood & Benzoin)", desc:"Perpaduan elegan bunga & kayu, best seller, EDP level.", price:"Rp 295.000 (10ml) / Rp 900.000 (60ml)" },
      { id:"butterfly_06", name:"Butterfly Parfum Original (Petrichor)", desc:"Lavender, geranium mawar & bergamot, tenang & segar.", price:"Rp 295.000 (10ml) / Rp 900.000 (60ml)" },
      { id:"butterfly_07", name:"Butterfly Hanging Parfum 10ml", desc:"Parfum gantung mobil, aroma tahan lama, banyak varian.", price:"Rp 245.000 (10ml)" },
      { id:"butterfly_08", name:"Butterfly Hang Cream", desc:"Hand cream floral-pear, mangga, atau woody-resin.", price:"Rp 225.000" }
    ]
  },
  gw: {
    name: "GENTLEWOMAN",
    tagline: "Bags & Accessories",
    accent: "#1A1A1A",
    accent2: "#C9A876",
    products: [
      { id:"gw_01", name:"GW Dumpling Bag", desc:"Tas dumpling ikonik, bentuk bulat lembut, 8 pilihan warna.", price:"Rp 875.000" },
      { id:"gw_02", name:"GW Shoulder Bag Ada Magnet", desc:"Tas selempang kulit, embossed logo, kancing magnet.", price:"Rp 1.135.000" },
      { id:"gw_03", name:"GW Strap Handphone", desc:"Gantungan tas manik bintang biru-putih, aksen charm logo.", price:"Rp 325.000" },
      { id:"gw_04", name:"GW Racket Pouch", desc:"Tas raket tenis motif Wiggle Resort, 2 pilihan motif.", price:"Rp 785.000" },
      { id:"gw_05", name:"GentleWoman Knit Dumpling Bag", desc:"Bahan rajut lembut, logo besar kontras, ringan & eye-catching.", price:"Rp 1.025.000" },
      { id:"gw_06", name:"GentleWoman x Moomin Denim Dumpling Bag", desc:"Kolaborasi Moomin, ada koin pouch karakter, unik & lucu.", price:"Rp 1.400.000" },
      { id:"gw_07", name:"Solea Dumpling Bag", desc:"Bahan kulit, logo embossed timbul, elegan & minimalis.", price:"Rp 1.155.000" },
      { id:"gw_08", name:"Sling Bag Mini Kanvas", desc:"Logo hitam-putih klasik, kanvas tebal, kasual.", price:"Rp 650.000" },
      { id:"gw_09", name:"Totebag Jumbo Kanvas No Klip Magnet", desc:"Ukuran besar, muat banyak, cocok harian/kuliah/kerja.", price:"Rp 475.000" },
      { id:"gw_10", name:"GentleWoman Club Leather Tote Bag w Zipper", desc:"Logo embossed, ada resleting, tali panjang, elegan.", price:"Rp 1.075.000" },
      { id:"gw_11", name:"GW Club Leather Tote Bag (Small/Mini)", desc:"Ukuran ringkas, tersedia warna cokelat & taupe.", price:"Rp 1.075.000" },
      { id:"gw_12", name:"Totebag Jumbo Bintang Bahan Kanvas", desc:"Warna cream, patch bunga & bintang, edisi dekoratif.", price:"Rp 1.125.000" },
      { id:"gw_13", name:"GentleWoman Mini Tote Bag Ribbon Logo Strap", desc:"Tali logo berulang, bentuk kotak ringkas, hitam & putih.", price:"Rp 450.000" },
      { id:"gw_14", name:"Totebag Jumbo Kanvas & Leather", desc:"Dalam kanvas, luar leather, warna camel, serbaguna.", price:"Rp 1.200.000" },
      { id:"gw_15", name:"Totebag Mat Corduroy", desc:"Warna peach, logo bordir merah-hijau kontras, vibrant.", price:"Rp 575.000" },
      { id:"gw_16", name:"Totebag Two Tone Mat Corduroy", desc:"Dua warna krem-hitam, logo bordir besar, kasual & bold.", price:"Rp 575.000" },
      { id:"gw_17", name:"Totebag Pocket Mat Kanvas", desc:"Warna hijau, saku depan pink kontras, eye-catching.", price:"Rp 475.000" }
    ]
  },
  erawadee: {
    name: "ERAWADEE",
    tagline: "Thailand Herbal & Wellness",
    accent: "#1E7A4C",
    accent2: "#7c39b7",
    products: [
      { id:"erawadee_01", name:"Erawadee Herbal Spray No.60", desc:"Mampu meredakan sakit dalam waktu 10-15 menit.", price:"Rp 495.000 (30ml) / Rp 700.000 (85ml)" },
      { id:"erawadee_02", name:"Erawadee Crystal Deodorant", desc:"Mineral alami tawas, bunuh bakteri penyebab bau badan & kontrol keringat berlebih.", price:"Rp 115.000" },
      { id:"erawadee_03", name:"Erawadee Black Spray Acne", desc:"Terbuat dari akar daun tapak budha, tanpa pewarna & pewangi, efektif sebagai obat semprot jerawat.", price:"Rp 395.000" },
      { id:"erawadee_04", name:"Erawadee Syn Ake Cream", desc:"Cream wajah diformulasikan khusus untuk menghilangkan melasma (flek).", price:"Rp 1.250.000" },
      { id:"erawadee_05", name:"Erawadee Roll On", desc:"10 macam minyak essential & ginseng, untuk sakit kepala, mual, pusing, mabuk laut, hidung mampet.", price:"Rp 90.000 (8ml)" },
      { id:"erawadee_06", name:"Erawadee Gingo Biloba", desc:"Untuk pendarahan otak, meningkatkan daya ingat & mikro sirkulasi pembuluh otak.", price:"Rp 470.000 (100 cap)" },
      { id:"erawadee_07", name:"Erawadee Kariyat", desc:"Mengobati pilek, mencegah infeksi, aktivitas anti virus & meningkatkan ketahanan tubuh.", price:"Rp 375.000 (100 cap)" },
      { id:"erawadee_08", name:"Erawadee Garcinia", desc:"Menekan nafsu makan, menunda rasa lapar & memberikan rasa kenyang.", price:"Rp 480.000 (100 cap)" },
      { id:"erawadee_09", name:"Erawadee Pla Lai Phueak", desc:"Mengembalikan kebugaran badan, mencegah ED, memperbaiki kualitas sperma.", price:"Rp 1.250.000 (100 cap)" },
      { id:"erawadee_10", name:"Erawadee No.100 Tang Tang Hae Chao", desc:"Formula botani untuk dukungan harian energi, stamina & kepercayaan diri.", price:"Rp 850.000 (10 cap)" }
    ]
  }
};
